<?php

namespace Saleka\BibliothequeBundle\Repository;

/**
 * FormatEditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatEditionRepository extends \Doctrine\ORM\EntityRepository
{
}
