<?php

namespace Saleka\BibliothequeBundle\Repository;

/**
 * LangueOeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangueOeuvreRepository extends \Doctrine\ORM\EntityRepository
{
}
