<?php

namespace Saleka\BibliothequeBundle\Repository;

/**
 * NatureEditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureEditionRepository extends \Doctrine\ORM\EntityRepository
{
}
