<?php

namespace Saleka\BibliothequeBundle\Repository;

/**
 * OeuvreEditionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreEditionRepository extends \Doctrine\ORM\EntityRepository
{
}
